/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as DexRouteImport } from './routes/dex'
import { Route as DropRouteImport } from './routes/drop'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as ReconstructRouteImport } from './routes/reconstruct'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StageRouteImport } from './routes/stage'
import { Route as StoryboardRouteImport } from './routes/storyboard'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStoryboardRouteImport } from './routes/api/storyboard'
import { Route as EmbedMintRouteImport } from './routes/embed.mint'
import { Route as IntakeGuidedRouteImport } from './routes/intake.guided'
import { Route as IntakeTellRouteImport } from './routes/intake.tell'
import { Route as IntakeUploadRouteImport } from './routes/intake.upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHolofoilRegisterRouteImport } from './routes/api/holofoil/register'
import { Route as InternalProofsHoodTerpsRouteImport } from './routes/internal/proofs/hood-terps'
import { Route as ApiHolofoilAssetIdTelemetryRouteImport } from './routes/api/holofoil/$assetId.telemetry'
import { Route as ApiHolofoilHallHallIdRouteImport } from './routes/api/holofoil/hall.$hallId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DexRoute = DexRouteImport.update({
  id: '/dex',
  path: '/dex',
  getParentRoute: () => rootRouteImport,
} as any)
const DropRoute = DropRouteImport.update({
  id: '/drop',
  path: '/drop',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconstructRoute = ReconstructRouteImport.update({
  id: '/reconstruct',
  path: '/reconstruct',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StageRoute = StageRouteImport.update({
  id: '/stage',
  path: '/stage',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardRoute = StoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryboardRoute = ApiStoryboardRouteImport.update({
  id: '/api/storyboard',
  path: '/api/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedMintRoute = EmbedMintRouteImport.update({
  id: '/embed/mint',
  path: '/embed/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeGuidedRoute = IntakeGuidedRouteImport.update({
  id: '/guided',
  path: '/guided',
  getParentRoute: () => IntakeRoute,
} as any)
const IntakeTellRoute = IntakeTellRouteImport.update({
  id: '/tell',
  path: '/tell',
  getParentRoute: () => IntakeRoute,
} as any)
const IntakeUploadRoute = IntakeUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => IntakeRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHolofoilRegisterRoute = ApiHolofoilRegisterRouteImport.update({
  id: '/api/holofoil/register',
  path: '/api/holofoil/register',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalProofsHoodTerpsRoute = InternalProofsHoodTerpsRouteImport.update({
  id: '/internal/proofs/hood-terps',
  path: '/internal/proofs/hood-terps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHolofoilAssetIdTelemetryRoute =
  ApiHolofoilAssetIdTelemetryRouteImport.update({
    id: '/api/holofoil/$assetId/telemetry',
    path: '/api/holofoil/$assetId/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHolofoilHallHallIdRoute = ApiHolofoilHallHallIdRouteImport.update({
  id: '/api/holofoil/hall/$hallId',
  path: '/api/holofoil/hall/$hallId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dex': typeof DexRoute
  '/drop': typeof DropRoute
  '/intake': typeof IntakeRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/project': typeof ProjectRoute
  '/proof': typeof ProofRoute
  '/reconstruct': typeof ReconstructRoute
  '/sdk': typeof SdkRoute
  '/services': typeof ServicesRoute
  '/stage': typeof StageRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storyboard': typeof ApiStoryboardRoute
  '/embed/mint': typeof EmbedMintRoute
  '/intake/guided': typeof IntakeGuidedRoute
  '/intake/tell': typeof IntakeTellRoute
  '/intake/upload': typeof IntakeUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/holofoil/register': typeof ApiHolofoilRegisterRoute
  '/internal/proofs/hood-terps': typeof InternalProofsHoodTerpsRoute
  '/api/holofoil/$assetId/telemetry': typeof ApiHolofoilAssetIdTelemetryRoute
  '/api/holofoil/hall/$hallId': typeof ApiHolofoilHallHallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dex': typeof DexRoute
  '/drop': typeof DropRoute
  '/intake': typeof IntakeRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/project': typeof ProjectRoute
  '/proof': typeof ProofRoute
  '/reconstruct': typeof ReconstructRoute
  '/sdk': typeof SdkRoute
  '/services': typeof ServicesRoute
  '/stage': typeof StageRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storyboard': typeof ApiStoryboardRoute
  '/embed/mint': typeof EmbedMintRoute
  '/intake/guided': typeof IntakeGuidedRoute
  '/intake/tell': typeof IntakeTellRoute
  '/intake/upload': typeof IntakeUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/holofoil/register': typeof ApiHolofoilRegisterRoute
  '/internal/proofs/hood-terps': typeof InternalProofsHoodTerpsRoute
  '/api/holofoil/$assetId/telemetry': typeof ApiHolofoilAssetIdTelemetryRoute
  '/api/holofoil/hall/$hallId': typeof ApiHolofoilHallHallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dex': typeof DexRoute
  '/drop': typeof DropRoute
  '/intake': typeof IntakeRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/project': typeof ProjectRoute
  '/proof': typeof ProofRoute
  '/reconstruct': typeof ReconstructRoute
  '/sdk': typeof SdkRoute
  '/services': typeof ServicesRoute
  '/stage': typeof StageRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storyboard': typeof ApiStoryboardRoute
  '/embed/mint': typeof EmbedMintRoute
  '/intake/guided': typeof IntakeGuidedRoute
  '/intake/tell': typeof IntakeTellRoute
  '/intake/upload': typeof IntakeUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/holofoil/register': typeof ApiHolofoilRegisterRoute
  '/internal/proofs/hood-terps': typeof InternalProofsHoodTerpsRoute
  '/api/holofoil/$assetId/telemetry': typeof ApiHolofoilAssetIdTelemetryRoute
  '/api/holofoil/hall/$hallId': typeof ApiHolofoilHallHallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/dex'
    | '/drop'
    | '/intake'
    | '/lab'
    | '/login'
    | '/project'
    | '/proof'
    | '/reconstruct'
    | '/sdk'
    | '/services'
    | '/stage'
    | '/storyboard'
    | '/studio'
    | '/api/generate'
    | '/api/health'
    | '/api/storyboard'
    | '/embed/mint'
    | '/intake/guided'
    | '/intake/tell'
    | '/intake/upload'
    | '/api/auth/$'
    | '/api/holofoil/register'
    | '/internal/proofs/hood-terps'
    | '/api/holofoil/$assetId/telemetry'
    | '/api/holofoil/hall/$hallId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/dex'
    | '/drop'
    | '/intake'
    | '/lab'
    | '/login'
    | '/project'
    | '/proof'
    | '/reconstruct'
    | '/sdk'
    | '/services'
    | '/stage'
    | '/storyboard'
    | '/studio'
    | '/api/generate'
    | '/api/health'
    | '/api/storyboard'
    | '/embed/mint'
    | '/intake/guided'
    | '/intake/tell'
    | '/intake/upload'
    | '/api/auth/$'
    | '/api/holofoil/register'
    | '/internal/proofs/hood-terps'
    | '/api/holofoil/$assetId/telemetry'
    | '/api/holofoil/hall/$hallId'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/dex'
    | '/drop'
    | '/intake'
    | '/lab'
    | '/login'
    | '/project'
    | '/proof'
    | '/reconstruct'
    | '/sdk'
    | '/services'
    | '/stage'
    | '/storyboard'
    | '/studio'
    | '/api/generate'
    | '/api/health'
    | '/api/storyboard'
    | '/embed/mint'
    | '/intake/guided'
    | '/intake/tell'
    | '/intake/upload'
    | '/api/auth/$'
    | '/api/holofoil/register'
    | '/internal/proofs/hood-terps'
    | '/api/holofoil/$assetId/telemetry'
    | '/api/holofoil/hall/$hallId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  DexRoute: typeof DexRoute
  DropRoute: typeof DropRoute
  IntakeRoute: typeof IntakeRouteWithChildren
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  ProjectRoute: typeof ProjectRoute
  ProofRoute: typeof ProofRoute
  ReconstructRoute: typeof ReconstructRoute
  SdkRoute: typeof SdkRoute
  ServicesRoute: typeof ServicesRoute
  StageRoute: typeof StageRoute
  StoryboardRoute: typeof StoryboardRoute
  StudioRoute: typeof StudioRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStoryboardRoute: typeof ApiStoryboardRoute
  EmbedMintRoute: typeof EmbedMintRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHolofoilRegisterRoute: typeof ApiHolofoilRegisterRoute
  InternalProofsHoodTerpsRoute: typeof InternalProofsHoodTerpsRoute
  ApiHolofoilAssetIdTelemetryRoute: typeof ApiHolofoilAssetIdTelemetryRoute
  ApiHolofoilHallHallIdRoute: typeof ApiHolofoilHallHallIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex': {
      id: '/dex'
      path: '/dex'
      fullPath: '/dex'
      preLoaderRoute: typeof DexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop': {
      id: '/drop'
      path: '/drop'
      fullPath: '/drop'
      preLoaderRoute: typeof DropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconstruct': {
      id: '/reconstruct'
      path: '/reconstruct'
      fullPath: '/reconstruct'
      preLoaderRoute: typeof ReconstructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage': {
      id: '/stage'
      path: '/stage'
      fullPath: '/stage'
      preLoaderRoute: typeof StageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storyboard': {
      id: '/api/storyboard'
      path: '/api/storyboard'
      fullPath: '/api/storyboard'
      preLoaderRoute: typeof ApiStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/mint': {
      id: '/embed/mint'
      path: '/embed/mint'
      fullPath: '/embed/mint'
      preLoaderRoute: typeof EmbedMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/guided': {
      id: '/intake/guided'
      path: '/guided'
      fullPath: '/intake/guided'
      preLoaderRoute: typeof IntakeGuidedRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/intake/tell': {
      id: '/intake/tell'
      path: '/tell'
      fullPath: '/intake/tell'
      preLoaderRoute: typeof IntakeTellRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/intake/upload': {
      id: '/intake/upload'
      path: '/upload'
      fullPath: '/intake/upload'
      preLoaderRoute: typeof IntakeUploadRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holofoil/register': {
      id: '/api/holofoil/register'
      path: '/api/holofoil/register'
      fullPath: '/api/holofoil/register'
      preLoaderRoute: typeof ApiHolofoilRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/proofs/hood-terps': {
      id: '/internal/proofs/hood-terps'
      path: '/internal/proofs/hood-terps'
      fullPath: '/internal/proofs/hood-terps'
      preLoaderRoute: typeof InternalProofsHoodTerpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holofoil/$assetId/telemetry': {
      id: '/api/holofoil/$assetId/telemetry'
      path: '/api/holofoil/$assetId/telemetry'
      fullPath: '/api/holofoil/$assetId/telemetry'
      preLoaderRoute: typeof ApiHolofoilAssetIdTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holofoil/hall/$hallId': {
      id: '/api/holofoil/hall/$hallId'
      path: '/api/holofoil/hall/$hallId'
      fullPath: '/api/holofoil/hall/$hallId'
      preLoaderRoute: typeof ApiHolofoilHallHallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IntakeRouteChildren {
  IntakeGuidedRoute: typeof IntakeGuidedRoute
  IntakeTellRoute: typeof IntakeTellRoute
  IntakeUploadRoute: typeof IntakeUploadRoute
}

const IntakeRouteChildren: IntakeRouteChildren = {
  IntakeGuidedRoute: IntakeGuidedRoute,
  IntakeTellRoute: IntakeTellRoute,
  IntakeUploadRoute: IntakeUploadRoute,
}

const IntakeRouteWithChildren =
  IntakeRoute._addFileChildren(IntakeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  DexRoute: DexRoute,
  DropRoute: DropRoute,
  IntakeRoute: IntakeRouteWithChildren,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  ProjectRoute: ProjectRoute,
  ProofRoute: ProofRoute,
  ReconstructRoute: ReconstructRoute,
  SdkRoute: SdkRoute,
  ServicesRoute: ServicesRoute,
  StageRoute: StageRoute,
  StoryboardRoute: StoryboardRoute,
  StudioRoute: StudioRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStoryboardRoute: ApiStoryboardRoute,
  EmbedMintRoute: EmbedMintRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHolofoilRegisterRoute: ApiHolofoilRegisterRoute,
  InternalProofsHoodTerpsRoute: InternalProofsHoodTerpsRoute,
  ApiHolofoilAssetIdTelemetryRoute: ApiHolofoilAssetIdTelemetryRoute,
  ApiHolofoilHallHallIdRoute: ApiHolofoilHallHallIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
