/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as DexRouteImport } from './routes/dex'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as StageRouteImport } from './routes/stage'
import { Route as StoryboardRouteImport } from './routes/storyboard'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStoryboardRouteImport } from './routes/api/storyboard'
import { Route as ApiHolofoilRegisterRouteImport } from './routes/api/holofoil/register'
import { Route as InternalProofsHoodTerpsRouteImport } from './routes/internal/proofs/hood-terps'
import { Route as ApiHolofoilAssetIdTelemetryRouteImport } from './routes/api/holofoil/$assetId.telemetry'
import { Route as ApiHolofoilHallHallIdRouteImport } from './routes/api/holofoil/hall.$hallId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DexRoute = DexRouteImport.update({
  id: '/dex',
  path: '/dex',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const StageRoute = StageRouteImport.update({
  id: '/stage',
  path: '/stage',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardRoute = StoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryboardRoute = ApiStoryboardRouteImport.update({
  id: '/api/storyboard',
  path: '/api/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHolofoilRegisterRoute = ApiHolofoilRegisterRouteImport.update({
  id: '/api/holofoil/register',
  path: '/api/holofoil/register',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalProofsHoodTerpsRoute = InternalProofsHoodTerpsRouteImport.update({
  id: '/internal/proofs/hood-terps',
  path: '/internal/proofs/hood-terps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHolofoilAssetIdTelemetryRoute =
  ApiHolofoilAssetIdTelemetryRouteImport.update({
    id: '/api/holofoil/$assetId/telemetry',
    path: '/api/holofoil/$assetId/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHolofoilHallHallIdRoute = ApiHolofoilHallHallIdRouteImport.update({
  id: '/api/holofoil/hall/$hallId',
  path: '/api/holofoil/hall/$hallId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dex': typeof DexRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/proof': typeof ProofRoute
  '/sdk': typeof SdkRoute
  '/stage': typeof StageRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storyboard': typeof ApiStoryboardRoute
  '/api/holofoil/register': typeof ApiHolofoilRegisterRoute
  '/internal/proofs/hood-terps': typeof InternalProofsHoodTerpsRoute
  '/api/holofoil/$assetId/telemetry': typeof ApiHolofoilAssetIdTelemetryRoute
  '/api/holofoil/hall/$hallId': typeof ApiHolofoilHallHallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dex': typeof DexRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/proof': typeof ProofRoute
  '/sdk': typeof SdkRoute
  '/stage': typeof StageRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storyboard': typeof ApiStoryboardRoute
  '/api/holofoil/register': typeof ApiHolofoilRegisterRoute
  '/internal/proofs/hood-terps': typeof InternalProofsHoodTerpsRoute
  '/api/holofoil/$assetId/telemetry': typeof ApiHolofoilAssetIdTelemetryRoute
  '/api/holofoil/hall/$hallId': typeof ApiHolofoilHallHallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dex': typeof DexRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/proof': typeof ProofRoute
  '/sdk': typeof SdkRoute
  '/stage': typeof StageRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/storyboard': typeof ApiStoryboardRoute
  '/api/holofoil/register': typeof ApiHolofoilRegisterRoute
  '/internal/proofs/hood-terps': typeof InternalProofsHoodTerpsRoute
  '/api/holofoil/$assetId/telemetry': typeof ApiHolofoilAssetIdTelemetryRoute
  '/api/holofoil/hall/$hallId': typeof ApiHolofoilHallHallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/dex'
    | '/lab'
    | '/login'
    | '/proof'
    | '/sdk'
    | '/stage'
    | '/storyboard'
    | '/studio'
    | '/api/generate'
    | '/api/health'
    | '/api/storyboard'
    | '/api/holofoil/register'
    | '/internal/proofs/hood-terps'
    | '/api/holofoil/$assetId/telemetry'
    | '/api/holofoil/hall/$hallId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/dex'
    | '/lab'
    | '/login'
    | '/proof'
    | '/sdk'
    | '/stage'
    | '/storyboard'
    | '/studio'
    | '/api/generate'
    | '/api/health'
    | '/api/storyboard'
    | '/api/holofoil/register'
    | '/internal/proofs/hood-terps'
    | '/api/holofoil/$assetId/telemetry'
    | '/api/holofoil/hall/$hallId'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/dex'
    | '/lab'
    | '/login'
    | '/proof'
    | '/sdk'
    | '/stage'
    | '/storyboard'
    | '/studio'
    | '/api/generate'
    | '/api/health'
    | '/api/storyboard'
    | '/api/holofoil/register'
    | '/internal/proofs/hood-terps'
    | '/api/holofoil/$assetId/telemetry'
    | '/api/holofoil/hall/$hallId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  DexRoute: typeof DexRoute
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  ProofRoute: typeof ProofRoute
  SdkRoute: typeof SdkRoute
  StageRoute: typeof StageRoute
  StoryboardRoute: typeof StoryboardRoute
  StudioRoute: typeof StudioRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStoryboardRoute: typeof ApiStoryboardRoute
  ApiHolofoilRegisterRoute: typeof ApiHolofoilRegisterRoute
  InternalProofsHoodTerpsRoute: typeof InternalProofsHoodTerpsRoute
  ApiHolofoilAssetIdTelemetryRoute: typeof ApiHolofoilAssetIdTelemetryRoute
  ApiHolofoilHallHallIdRoute: typeof ApiHolofoilHallHallIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex': {
      id: '/dex'
      path: '/dex'
      fullPath: '/dex'
      preLoaderRoute: typeof DexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage': {
      id: '/stage'
      path: '/stage'
      fullPath: '/stage'
      preLoaderRoute: typeof StageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storyboard': {
      id: '/api/storyboard'
      path: '/api/storyboard'
      fullPath: '/api/storyboard'
      preLoaderRoute: typeof ApiStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holofoil/register': {
      id: '/api/holofoil/register'
      path: '/api/holofoil/register'
      fullPath: '/api/holofoil/register'
      preLoaderRoute: typeof ApiHolofoilRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/proofs/hood-terps': {
      id: '/internal/proofs/hood-terps'
      path: '/internal/proofs/hood-terps'
      fullPath: '/internal/proofs/hood-terps'
      preLoaderRoute: typeof InternalProofsHoodTerpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holofoil/$assetId/telemetry': {
      id: '/api/holofoil/$assetId/telemetry'
      path: '/api/holofoil/$assetId/telemetry'
      fullPath: '/api/holofoil/$assetId/telemetry'
      preLoaderRoute: typeof ApiHolofoilAssetIdTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holofoil/hall/$hallId': {
      id: '/api/holofoil/hall/$hallId'
      path: '/api/holofoil/hall/$hallId'
      fullPath: '/api/holofoil/hall/$hallId'
      preLoaderRoute: typeof ApiHolofoilHallHallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  DexRoute: DexRoute,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  ProofRoute: ProofRoute,
  SdkRoute: SdkRoute,
  StageRoute: StageRoute,
  StoryboardRoute: StoryboardRoute,
  StudioRoute: StudioRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStoryboardRoute: ApiStoryboardRoute,
  ApiHolofoilRegisterRoute: ApiHolofoilRegisterRoute,
  InternalProofsHoodTerpsRoute: InternalProofsHoodTerpsRoute,
  ApiHolofoilAssetIdTelemetryRoute: ApiHolofoilAssetIdTelemetryRoute,
  ApiHolofoilHallHallIdRoute: ApiHolofoilHallHallIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
